// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PermissionModalController from "./permission_modal_controller"
application.register("permission-modal", PermissionModalController)

import RuleFormController from "./rule_form_controller"
application.register("rule-form", RuleFormController)
